version: 2

sources:
  - name: gz_raw_data
    schema: gz_raw_data
    description: greenweez raw data source   
    tables:
      - name: product
        identifier: raw_gz_product
        description: sales of greenweez/ we have one row per products_id.
        columns:
          - name: products_id
            description: pk of product
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: define the purchasing price for each product.
   
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez/ we have one row per products_id found in each orders_id. 
        tests:
              - unique:
                 column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: date_date
            description: the date of purchase.
          - name: qty
            description: define the quantity of a product that have been purchased. 
          - name: revenue
            description: turnover for each products_id and orders_id(unique as pk)
          - name: orders_id
            description: join key for ship table and PK in combine with products_id.
          - name: products_id
            description: join key for product table and PK in combine with orders_id.
            
              
      - name: ship
        identifier: raw_gz_ship
        description: shipping(inventory) of greenweez/ we have one row per orders_id.
        columns:
          - name: shipping_fee
            description: define the shipping price on the customer for eacsh order.
          - name: logcost
            description: logistic costs per order.
          - name: ship_cost
            description: how much shipping cost for each order.
          - name: orders_id
            description: PK ship table.
            tests:
              - unique
              - not_null


